### PR TITLE
Added eslint

### PR DESCRIPTION
**Pull request by yotamN**
I think all the modules should have a linter, I added it here but do you think it should be added to the rest of the modules?

### CODE REVIEW

**Comment by WebReflection** [comment]
I am **very** skeptical against linters ... I am for the least amount of rules. Can you explain what this preset impose? I mostly hate stubborn linters and I don't want to debate against stubborn linters rules.

Thanks for clarifying about this

**Comment by WebReflection** [comment]
Hey @yotamN mind changing the eslint config as such?

```js
{
  "extends": "eslint:recommended",
  "globals": {
    "Promise": true,
    "imports": true
  },
  "rules": {
    "no-case-declarations": 0,
    "no-fallthrough": 0
  }
}
```

this seems to be way more reasonable than airbnb bloated set of stubborn rules, IMO.

Thanks

**Comment by WebReflection** [comment]
actually, never mind. I've pushed the default `.eslintrc` to all repositories in here so please remove your file from this PR, thanks.

**Comment by yotamN** [comment]
I have changed the eslint config, there are other changes in the pull request, fixed a function that was missing a commit from the previous pull request

**Comment by WebReflection** [comment]
hey @yotamN I've published this as 0.0.1 and added to cgjs latest version.
Even if incomplete, it's now usable for what it offers via cgjs, thanks again!

**Pull request merged**
