### PR TITLE
Added readFileSync function

### PR DESCRIPTION
**Pull request by yotamN**

### CODE REVIEW

**Comment by WebReflection** [comment]
thanks! do you mind dropping that editor config file in `.npmignore` ?

**Comment by yotamN** [comment]
I added the editor config file to `.npmignore`

**Comment by WebReflection** [comment]
FYI this is half of the job. If you want the module to land in core you need to add it as [dependency](https://github.com/cgjs/cgjs/blob/master/package.json#L31) and then eventually as [core module](https://github.com/cgjs/cgjs/blob/master/cgjs/core.js#L8).

Although, I'm not sure with only one method it makes sense to have the `fs` core module shipped already ... thoughts ?

**Comment by yotamN** [comment]
I don't think it will be very useful, it's not even complete yet (the function ignore the flag paramter). I hope to add more functions in the next few days and then maybe add it as a dependency.

**Comment by WebReflection** [comment]
FWIW I am trying to bring stream core module in, which is used by 90% of NodeJS API including files. I'm a bit lost though because `imports.byteArray` seems to work better with GLib and I am not sure anymore having the buffer from Node makes sense in here ... however, raw performance is not currently a goal

**Comment by yotamN** [comment]
I'm not sure I understand. I return a `Buffer` because that is the API in Node, I'm not sure actually what are the diffrences between `imports.byteArray` and `Buffer`

**Comment by WebReflection** [comment]
I am using exact same Buffer from Node, it's literally the same module. However, the GJS equivalent of Node `buffer` module is `imports.byteArray` because of this (quoting Giovanni)

> One of the reasons ByteArray exists is that it wraps GByteArray and GBytes from glib.
> In particular for GBytes, it means that, as long as you don't modify the underlying store, you can pass around binary data between libraries with no copies.
> I don't know if JS UInt8Arrays allow that, and I worry they would not - at the very least, it would be hard to do the copy-on-write behavior ByteArray has.
>
> At the same time, as you point out in the bug, GLib.Bytes exists and would not go away.
> It could be extended to do field access so that JS can read the actual data, removing the need to wrap it in a zero-copy ByteArray.

**Comment by WebReflection** [comment]
that was from the ML and @gcampax

**Comment by WebReflection** [comment]
Just to clarify, I'd eventually make `require("buffer")` an API compatible module even if the underlying class is `byteArray` and not the NodeJS core code ... so, technically there's nothing to change in here.

It was rather sharing knowledge or current project status: streams are the highest priority but contributing for other parts of the core that don't need streams is more than welcome, thanks!

**Pull request merged**
